# dataset
dataset: HTGReDial
tokenize: pkuseg
# dataloader
related_truncate: 1024
context_truncate: 256
response_truncate: 30
scale: 1
# model
model: MHIM
token_emb_dim: 300
kg_emb_dim: 128
num_bases: 8
n_heads: 2
n_layers: 2
ffn_size: 300
dropout: 0.1
attention_dropout: 0.0
relu_dropout: 0.1
learn_positional_embeddings: false
embeddings_scale: true
reduction: false
n_positions: 1024
user_proj_dim: 512
# MHIM-CHANGE
mha_n_heads: 4
pooling: Attn
extension_strategy: Adaptive
# optim
rec:
  epoch: 1
  batch_size: 64
  early_stop: True
  stop_mode: min
  impatience: 2
  optimizer:
    name: Adam
    lr: !!float 1e-3
conv:
  epoch: 1
  batch_size: 128
  impatience: 1
  optimizer:
    name: Adam
    lr: !!float 1e-3
  lr_scheduler:
    name: ReduceLROnPlateau
    patience: 3
    factor: 0.5
  gradient_clip: 0.1