# general
seed: 2022
gpu: 0
log_path: 'log/tgredial.log'
checkpoint_path: 'save/tgredial'

# data
graph_path: 'data/tgredial/data.bin'
meta_path: 'data/tgredial/embedding_meta_data.pkl'
random_walk_hops: 128
restart_prob: 0.5
sample_num: 12288

# model
emb_dim: 128
n_relation: 56
n_bases: 8

# moco
alpha: 0.999
queue_size: 16384
temperature: 0.07
use_softmax: True

# optimizer
batch_size: 1024
learning_rate: 0.005
beta1: 0.9
beta2: 0.999
weight_decay: !!float 1e-5
epochs: 11
lr_decay_rate: 0.0
lr_decay_epochs: [120, 160, 200]
clip_norm: 1.0